#Script Install Packages
install.packages("htmltools")
install.packages("dplyr")
install.packages("stringr")
install.packages("lubridate")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("datetime")
install.packages("leaflet")
install.packages("shiny")
install.packages("RColorBrewer")
install.packages("crosstalk")


library("RColorBrewer")
library("shiny")
library("htmltools")
library("leaflet")
library("dplyr")
library("stringr")
library("lubridate")
library("tidyverse")
library("ggplot2")
library("datetime")